//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 03:44:18 PM GMT 
//


package org.hisp.dhis.importexport.dxf.v2object;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://dhis2.org/ns/schema/dxf2}identifiableObject">
 *       &lt;sequence>
 *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}active"/>
 *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}type"/>
 *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}aggregationOperator"/>
 *         &lt;element name="categoryCombo" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "active",
    "type",
    "aggregationOperator",
    "categoryCombo"
})
@XmlRootElement(name = "dataElement")
public class DataElement
    extends IdentifiableObject
{

    @XmlElement(required = true)
    protected String active;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String aggregationOperator;
    @XmlElement(required = true)
    protected BigInteger categoryCombo;

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActive(String value) {
        this.active = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the aggregationOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregationOperator() {
        return aggregationOperator;
    }

    /**
     * Sets the value of the aggregationOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregationOperator(String value) {
        this.aggregationOperator = value;
    }

    /**
     * Gets the value of the categoryCombo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCategoryCombo() {
        return categoryCombo;
    }

    /**
     * Sets the value of the categoryCombo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCategoryCombo(BigInteger value) {
        this.categoryCombo = value;
    }

}
