//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 03:44:18 PM GMT 
//


package org.hisp.dhis.importexport.dxf.v2object;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="indicator" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://dhis2.org/ns/schema/dxf2}identifiableObject">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}annualized"/>
 *                   &lt;element name="indicatorType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}numerator"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}numeratorDescription"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}numeratorAggregationOperator"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}denominator"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}denominatorDescription"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}denominatorAggregationOperator"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "indicator"
})
@XmlRootElement(name = "indicators")
public class Indicators {

    protected List<Indicators.Indicator> indicator;

    /**
     * Gets the value of the indicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Indicators.Indicator }
     * 
     * 
     */
    public List<Indicators.Indicator> getIndicator() {
        if (indicator == null) {
            indicator = new ArrayList<Indicators.Indicator>();
        }
        return this.indicator;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://dhis2.org/ns/schema/dxf2}identifiableObject">
     *       &lt;sequence>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}annualized"/>
     *         &lt;element name="indicatorType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}numerator"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}numeratorDescription"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}numeratorAggregationOperator"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}denominator"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}denominatorDescription"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}denominatorAggregationOperator"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "annualized",
        "indicatorType",
        "numerator",
        "numeratorDescription",
        "numeratorAggregationOperator",
        "denominator",
        "denominatorDescription",
        "denominatorAggregationOperator"
    })
    public static class Indicator
        extends IdentifiableObject
    {

        @XmlElement(required = true)
        protected String annualized;
        @XmlElement(required = true)
        protected BigInteger indicatorType;
        @XmlElement(required = true)
        protected String numerator;
        @XmlElement(required = true)
        protected String numeratorDescription;
        @XmlElement(required = true)
        protected String numeratorAggregationOperator;
        @XmlElement(required = true)
        protected String denominator;
        @XmlElement(required = true)
        protected String denominatorDescription;
        @XmlElement(required = true)
        protected String denominatorAggregationOperator;

        /**
         * Gets the value of the annualized property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnnualized() {
            return annualized;
        }

        /**
         * Sets the value of the annualized property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnnualized(String value) {
            this.annualized = value;
        }

        /**
         * Gets the value of the indicatorType property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIndicatorType() {
            return indicatorType;
        }

        /**
         * Sets the value of the indicatorType property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIndicatorType(BigInteger value) {
            this.indicatorType = value;
        }

        /**
         * Gets the value of the numerator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumerator() {
            return numerator;
        }

        /**
         * Sets the value of the numerator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumerator(String value) {
            this.numerator = value;
        }

        /**
         * Gets the value of the numeratorDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeratorDescription() {
            return numeratorDescription;
        }

        /**
         * Sets the value of the numeratorDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeratorDescription(String value) {
            this.numeratorDescription = value;
        }

        /**
         * Gets the value of the numeratorAggregationOperator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeratorAggregationOperator() {
            return numeratorAggregationOperator;
        }

        /**
         * Sets the value of the numeratorAggregationOperator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeratorAggregationOperator(String value) {
            this.numeratorAggregationOperator = value;
        }

        /**
         * Gets the value of the denominator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDenominator() {
            return denominator;
        }

        /**
         * Sets the value of the denominator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDenominator(String value) {
            this.denominator = value;
        }

        /**
         * Gets the value of the denominatorDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDenominatorDescription() {
            return denominatorDescription;
        }

        /**
         * Sets the value of the denominatorDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDenominatorDescription(String value) {
            this.denominatorDescription = value;
        }

        /**
         * Gets the value of the denominatorAggregationOperator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDenominatorAggregationOperator() {
            return denominatorAggregationOperator;
        }

        /**
         * Sets the value of the denominatorAggregationOperator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDenominatorAggregationOperator(String value) {
            this.denominatorAggregationOperator = value;
        }

    }

}
