//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 03:44:18 PM GMT 
//


package org.hisp.dhis.importexport.dxf.v2object;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hisp.dhis.importexport.dxf.v2object package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Type_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "type");
    private final static QName _NumeratorAggregationOperator_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "numeratorAggregationOperator");
    private final static QName _Regression_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "regression");
    private final static QName _EndDate_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "endDate");
    private final static QName _ParamReportingMonth_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "paramReportingMonth");
    private final static QName _Last12Months_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last12Months");
    private final static QName _Last9To12Months_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last9To12Months");
    private final static QName _Description_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "description");
    private final static QName _ReportingMonth_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "reportingMonth");
    private final static QName _Level_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "level");
    private final static QName _Last6Months_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last6Months");
    private final static QName _ParamOrganisationUnit_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "paramOrganisationUnit");
    private final static QName _Parent_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "parent");
    private final static QName _Code_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "code");
    private final static QName _CategoryOption_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "categoryOption");
    private final static QName _Numerator_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "numerator");
    private final static QName _AggregationOperator_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "aggregationOperator");
    private final static QName _IndicatorId_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "IndicatorId");
    private final static QName _CategoryId_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "categoryId");
    private final static QName _Last6To9Months_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last6To9Months");
    private final static QName _DoPeriods_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "doPeriods");
    private final static QName _SortOrder_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "sortOrder");
    private final static QName _Compulsory_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "compulsory");
    private final static QName _Comment_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "comment");
    private final static QName _Active_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "active");
    private final static QName _DoCategoryOptionCombos_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "doCategoryOptionCombos");
    private final static QName _SoFarThisFinancialYear_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "soFarThisFinancialYear");
    private final static QName _Uuid_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "uuid");
    private final static QName _PeriodType_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "periodType");
    private final static QName _ExistingTableName_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "existingTableName");
    private final static QName _CategoryComboId_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "categoryComboId");
    private final static QName _DenominatorDescription_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "denominatorDescription");
    private final static QName _Mode_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "mode");
    private final static QName _Last12IndividualMonths_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last12IndividualMonths");
    private final static QName _DoOrganisationUnits_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "doOrganisationUnits");
    private final static QName _NumeratorDescription_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "numeratorDescription");
    private final static QName _ClosedDate_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "closedDate");
    private final static QName _DataElementId_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "dataElementId");
    private final static QName _Exclusive_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "exclusive");
    private final static QName _StartDate_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "startDate");
    private final static QName _Region_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "region");
    private final static QName _Annualized_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "annualized");
    private final static QName _ParamParentOrganisationUnit_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "paramParentOrganisationUnit");
    private final static QName _DenominatorAggregationOperator_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "denominatorAggregationOperator");
    private final static QName _IndividualMonthsThisYear_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "individualMonthsThisYear");
    private final static QName _Shortname_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "shortname");
    private final static QName _Last9Months_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last9Months");
    private final static QName _Name_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "name");
    private final static QName _TableName_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "tableName");
    private final static QName _Id_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "id");
    private final static QName _Child_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "child");
    private final static QName _SoFarThisYear_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "soFarThisYear");
    private final static QName _Last3Months_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last3Months");
    private final static QName _GeoCode_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "geoCode");
    private final static QName _DoIndicators_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "doIndicators");
    private final static QName _Factor_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "factor");
    private final static QName _Denominator_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "denominator");
    private final static QName _Alternativename_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "alternativename");
    private final static QName _ShortName_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "shortName");
    private final static QName _CategoryOptionId_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "categoryOptionId");
    private final static QName _IndividualQuartersThisYear_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "individualQuartersThisYear");
    private final static QName _OpeningDate_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "openingDate");
    private final static QName _Source_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "source");
    private final static QName _Last3To6Months_QNAME = new QName("http://dhis2.org/ns/schema/dxf2", "last3To6Months");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hisp.dhis.importexport.dxf.v2object
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSets.DataSet }
     * 
     */
    public DataSets.DataSet createDataSetsDataSet() {
        return new DataSets.DataSet();
    }

    /**
     * Create an instance of {@link ReportTableOrganisationUnits }
     * 
     */
    public ReportTableOrganisationUnits createReportTableOrganisationUnits() {
        return new ReportTableOrganisationUnits();
    }

    /**
     * Create an instance of {@link IndicatorGroup }
     * 
     */
    public IndicatorGroup createIndicatorGroup() {
        return new IndicatorGroup();
    }

    /**
     * Create an instance of {@link OrganisationUnitGroups.OrganisationUnitGroup }
     * 
     */
    public OrganisationUnitGroups.OrganisationUnitGroup createOrganisationUnitGroupsOrganisationUnitGroup() {
        return new OrganisationUnitGroups.OrganisationUnitGroup();
    }

    /**
     * Create an instance of {@link CategoryCombos }
     * 
     */
    public CategoryCombos createCategoryCombos() {
        return new CategoryCombos();
    }

    /**
     * Create an instance of {@link DataSetMembers }
     * 
     */
    public DataSetMembers createDataSetMembers() {
        return new DataSetMembers();
    }

    /**
     * Create an instance of {@link Indicators }
     * 
     */
    public Indicators createIndicators() {
        return new Indicators();
    }

    /**
     * Create an instance of {@link DataDictionaryDataElements }
     * 
     */
    public DataDictionaryDataElements createDataDictionaryDataElements() {
        return new DataDictionaryDataElements();
    }

    /**
     * Create an instance of {@link IndicatorTypes.IndicatorType }
     * 
     */
    public IndicatorTypes.IndicatorType createIndicatorTypesIndicatorType() {
        return new IndicatorTypes.IndicatorType();
    }

    /**
     * Create an instance of {@link GroupSetMembers }
     * 
     */
    public GroupSetMembers createGroupSetMembers() {
        return new GroupSetMembers();
    }

    /**
     * Create an instance of {@link IndicatorTypes }
     * 
     */
    public IndicatorTypes createIndicatorTypes() {
        return new IndicatorTypes();
    }

    /**
     * Create an instance of {@link ReportTableDataSet }
     * 
     */
    public ReportTableDataSet createReportTableDataSet() {
        return new ReportTableDataSet();
    }

    /**
     * Create an instance of {@link Indicators.Indicator }
     * 
     */
    public Indicators.Indicator createIndicatorsIndicator() {
        return new Indicators.Indicator();
    }

    /**
     * Create an instance of {@link OrganisationUnitGroupMembers }
     * 
     */
    public OrganisationUnitGroupMembers createOrganisationUnitGroupMembers() {
        return new OrganisationUnitGroupMembers();
    }

    /**
     * Create an instance of {@link ReportTables }
     * 
     */
    public ReportTables createReportTables() {
        return new ReportTables();
    }

    /**
     * Create an instance of {@link DataDictionaries }
     * 
     */
    public DataDictionaries createDataDictionaries() {
        return new DataDictionaries();
    }

    /**
     * Create an instance of {@link DataDictionaries.DataDictionary }
     * 
     */
    public DataDictionaries.DataDictionary createDataDictionariesDataDictionary() {
        return new DataDictionaries.DataDictionary();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link ReportTableIndicators }
     * 
     */
    public ReportTableIndicators createReportTableIndicators() {
        return new ReportTableIndicators();
    }

    /**
     * Create an instance of {@link ReportTablePeriods }
     * 
     */
    public ReportTablePeriods createReportTablePeriods() {
        return new ReportTablePeriods();
    }

    /**
     * Create an instance of {@link DataDictionaryDataElement }
     * 
     */
    public DataDictionaryDataElement createDataDictionaryDataElement() {
        return new DataDictionaryDataElement();
    }

    /**
     * Create an instance of {@link ReportTableDataSets }
     * 
     */
    public ReportTableDataSets createReportTableDataSets() {
        return new ReportTableDataSets();
    }

    /**
     * Create an instance of {@link DataDictionaryIndicators }
     * 
     */
    public DataDictionaryIndicators createDataDictionaryIndicators() {
        return new DataDictionaryIndicators();
    }

    /**
     * Create an instance of {@link GroupSetMember }
     * 
     */
    public GroupSetMember createGroupSetMember() {
        return new GroupSetMember();
    }

    /**
     * Create an instance of {@link DataElementGroup }
     * 
     */
    public DataElementGroup createDataElementGroup() {
        return new DataElementGroup();
    }

    /**
     * Create an instance of {@link GroupSets }
     * 
     */
    public GroupSets createGroupSets() {
        return new GroupSets();
    }

    /**
     * Create an instance of {@link CompleteDataSetRegistrations }
     * 
     */
    public CompleteDataSetRegistrations createCompleteDataSetRegistrations() {
        return new CompleteDataSetRegistrations();
    }

    /**
     * Create an instance of {@link OrganisationUnitLevels }
     * 
     */
    public OrganisationUnitLevels createOrganisationUnitLevels() {
        return new OrganisationUnitLevels();
    }

    /**
     * Create an instance of {@link org.hisp.dhis.importexport.dxf.v2object.Categories }
     * 
     */
    public org.hisp.dhis.importexport.dxf.v2object.Categories createCategories() {
        return new org.hisp.dhis.importexport.dxf.v2object.Categories();
    }

    /**
     * Create an instance of {@link CategoryOptionCombo }
     * 
     */
    public CategoryOptionCombo createCategoryOptionCombo() {
        return new CategoryOptionCombo();
    }

    /**
     * Create an instance of {@link DataValues }
     * 
     */
    public DataValues createDataValues() {
        return new DataValues();
    }

    /**
     * Create an instance of {@link IdentifiableObject }
     * 
     */
    public IdentifiableObject createIdentifiableObject() {
        return new IdentifiableObject();
    }

    /**
     * Create an instance of {@link DataDictionaryIndicator }
     * 
     */
    public DataDictionaryIndicator createDataDictionaryIndicator() {
        return new DataDictionaryIndicator();
    }

    /**
     * Create an instance of {@link ReportTableDataElements }
     * 
     */
    public ReportTableDataElements createReportTableDataElements() {
        return new ReportTableDataElements();
    }

    /**
     * Create an instance of {@link CategoryCombo }
     * 
     */
    public CategoryCombo createCategoryCombo() {
        return new CategoryCombo();
    }

    /**
     * Create an instance of {@link ReportTables.ReportTable }
     * 
     */
    public ReportTables.ReportTable createReportTablesReportTable() {
        return new ReportTables.ReportTable();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link CategoryCombo.Categories }
     * 
     */
    public CategoryCombo.Categories createCategoryComboCategories() {
        return new CategoryCombo.Categories();
    }

    /**
     * Create an instance of {@link Periods }
     * 
     */
    public Periods createPeriods() {
        return new Periods();
    }

    /**
     * Create an instance of {@link IndicatorGroupSets }
     * 
     */
    public IndicatorGroupSets createIndicatorGroupSets() {
        return new IndicatorGroupSets();
    }

    /**
     * Create an instance of {@link GroupSets.GroupSet }
     * 
     */
    public GroupSets.GroupSet createGroupSetsGroupSet() {
        return new GroupSets.GroupSet();
    }

    /**
     * Create an instance of {@link DataSetSourceAssociations }
     * 
     */
    public DataSetSourceAssociations createDataSetSourceAssociations() {
        return new DataSetSourceAssociations();
    }

    /**
     * Create an instance of {@link DataSets }
     * 
     */
    public DataSets createDataSets() {
        return new DataSets();
    }

    /**
     * Create an instance of {@link DataElements }
     * 
     */
    public DataElements createDataElements() {
        return new DataElements();
    }

    /**
     * Create an instance of {@link IndicatorGroupSet }
     * 
     */
    public IndicatorGroupSet createIndicatorGroupSet() {
        return new IndicatorGroupSet();
    }

    /**
     * Create an instance of {@link ReportTableOrganisationUnit }
     * 
     */
    public ReportTableOrganisationUnit createReportTableOrganisationUnit() {
        return new ReportTableOrganisationUnit();
    }

    /**
     * Create an instance of {@link OrganisationUnitRelationships }
     * 
     */
    public OrganisationUnitRelationships createOrganisationUnitRelationships() {
        return new OrganisationUnitRelationships();
    }

    /**
     * Create an instance of {@link DataElementGroupSet }
     * 
     */
    public DataElementGroupSet createDataElementGroupSet() {
        return new DataElementGroupSet();
    }

    /**
     * Create an instance of {@link OrganisationUnitLevel }
     * 
     */
    public OrganisationUnitLevel createOrganisationUnitLevel() {
        return new OrganisationUnitLevel();
    }

    /**
     * Create an instance of {@link OrganisationUnitGroupMember }
     * 
     */
    public OrganisationUnitGroupMember createOrganisationUnitGroupMember() {
        return new OrganisationUnitGroupMember();
    }

    /**
     * Create an instance of {@link DataElementGroupSets }
     * 
     */
    public DataElementGroupSets createDataElementGroupSets() {
        return new DataElementGroupSets();
    }

    /**
     * Create an instance of {@link ReportTableIndicator }
     * 
     */
    public ReportTableIndicator createReportTableIndicator() {
        return new ReportTableIndicator();
    }

    /**
     * Create an instance of {@link Dxf }
     * 
     */
    public Dxf createDxf() {
        return new Dxf();
    }

    /**
     * Create an instance of {@link OrganisationUnit }
     * 
     */
    public OrganisationUnit createOrganisationUnit() {
        return new OrganisationUnit();
    }

    /**
     * Create an instance of {@link OrganisationUnitRelationship }
     * 
     */
    public OrganisationUnitRelationship createOrganisationUnitRelationship() {
        return new OrganisationUnitRelationship();
    }

    /**
     * Create an instance of {@link DataSetSourceAssociation }
     * 
     */
    public DataSetSourceAssociation createDataSetSourceAssociation() {
        return new DataSetSourceAssociation();
    }

    /**
     * Create an instance of {@link DataValue }
     * 
     */
    public DataValue createDataValue() {
        return new DataValue();
    }

    /**
     * Create an instance of {@link ReportTableCategoryOptionCombos }
     * 
     */
    public ReportTableCategoryOptionCombos createReportTableCategoryOptionCombos() {
        return new ReportTableCategoryOptionCombos();
    }

    /**
     * Create an instance of {@link OrganisationUnitGroups }
     * 
     */
    public OrganisationUnitGroups createOrganisationUnitGroups() {
        return new OrganisationUnitGroups();
    }

    /**
     * Create an instance of {@link CategoryOptionCombos }
     * 
     */
    public CategoryOptionCombos createCategoryOptionCombos() {
        return new CategoryOptionCombos();
    }

    /**
     * Create an instance of {@link DataElement }
     * 
     */
    public DataElement createDataElement() {
        return new DataElement();
    }

    /**
     * Create an instance of {@link OrganisationUnits }
     * 
     */
    public OrganisationUnits createOrganisationUnits() {
        return new OrganisationUnits();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "numeratorAggregationOperator")
    public JAXBElement<String> createNumeratorAggregationOperator(String value) {
        return new JAXBElement<String>(_NumeratorAggregationOperator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "regression")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRegression(String value) {
        return new JAXBElement<String>(_Regression_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "endDate")
    public JAXBElement<XMLGregorianCalendar> createEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "paramReportingMonth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParamReportingMonth(String value) {
        return new JAXBElement<String>(_ParamReportingMonth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last12Months")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast12Months(String value) {
        return new JAXBElement<String>(_Last12Months_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last9To12Months")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast9To12Months(String value) {
        return new JAXBElement<String>(_Last9To12Months_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "reportingMonth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReportingMonth(String value) {
        return new JAXBElement<String>(_ReportingMonth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "level")
    public JAXBElement<BigInteger> createLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_Level_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last6Months")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast6Months(String value) {
        return new JAXBElement<String>(_Last6Months_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "paramOrganisationUnit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParamOrganisationUnit(String value) {
        return new JAXBElement<String>(_ParamOrganisationUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "parent")
    public JAXBElement<BigInteger> createParent(BigInteger value) {
        return new JAXBElement<BigInteger>(_Parent_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "code")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifiableObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "categoryOption")
    public JAXBElement<IdentifiableObject> createCategoryOption(IdentifiableObject value) {
        return new JAXBElement<IdentifiableObject>(_CategoryOption_QNAME, IdentifiableObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "numerator")
    public JAXBElement<String> createNumerator(String value) {
        return new JAXBElement<String>(_Numerator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "aggregationOperator")
    public JAXBElement<String> createAggregationOperator(String value) {
        return new JAXBElement<String>(_AggregationOperator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "IndicatorId")
    public JAXBElement<BigInteger> createIndicatorId(BigInteger value) {
        return new JAXBElement<BigInteger>(_IndicatorId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "categoryId")
    public JAXBElement<BigInteger> createCategoryId(BigInteger value) {
        return new JAXBElement<BigInteger>(_CategoryId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last6To9Months")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast6To9Months(String value) {
        return new JAXBElement<String>(_Last6To9Months_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "doPeriods")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDoPeriods(String value) {
        return new JAXBElement<String>(_DoPeriods_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "sortOrder")
    public JAXBElement<BigInteger> createSortOrder(BigInteger value) {
        return new JAXBElement<BigInteger>(_SortOrder_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "compulsory")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCompulsory(String value) {
        return new JAXBElement<String>(_Compulsory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "comment")
    public JAXBElement<String> createComment(String value) {
        return new JAXBElement<String>(_Comment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "active")
    public JAXBElement<String> createActive(String value) {
        return new JAXBElement<String>(_Active_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "doCategoryOptionCombos")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDoCategoryOptionCombos(String value) {
        return new JAXBElement<String>(_DoCategoryOptionCombos_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "soFarThisFinancialYear")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSoFarThisFinancialYear(String value) {
        return new JAXBElement<String>(_SoFarThisFinancialYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "uuid")
    public JAXBElement<String> createUuid(String value) {
        return new JAXBElement<String>(_Uuid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "periodType")
    public JAXBElement<String> createPeriodType(String value) {
        return new JAXBElement<String>(_PeriodType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "existingTableName")
    public JAXBElement<String> createExistingTableName(String value) {
        return new JAXBElement<String>(_ExistingTableName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "categoryComboId")
    public JAXBElement<BigInteger> createCategoryComboId(BigInteger value) {
        return new JAXBElement<BigInteger>(_CategoryComboId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "denominatorDescription")
    public JAXBElement<String> createDenominatorDescription(String value) {
        return new JAXBElement<String>(_DenominatorDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "mode")
    public JAXBElement<String> createMode(String value) {
        return new JAXBElement<String>(_Mode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last12IndividualMonths")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast12IndividualMonths(String value) {
        return new JAXBElement<String>(_Last12IndividualMonths_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "doOrganisationUnits")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDoOrganisationUnits(String value) {
        return new JAXBElement<String>(_DoOrganisationUnits_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "numeratorDescription")
    public JAXBElement<String> createNumeratorDescription(String value) {
        return new JAXBElement<String>(_NumeratorDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "closedDate")
    public JAXBElement<String> createClosedDate(String value) {
        return new JAXBElement<String>(_ClosedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "dataElementId")
    public JAXBElement<BigInteger> createDataElementId(BigInteger value) {
        return new JAXBElement<BigInteger>(_DataElementId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "exclusive")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createExclusive(String value) {
        return new JAXBElement<String>(_Exclusive_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "startDate")
    public JAXBElement<XMLGregorianCalendar> createStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_StartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "region")
    public JAXBElement<String> createRegion(String value) {
        return new JAXBElement<String>(_Region_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "annualized")
    public JAXBElement<String> createAnnualized(String value) {
        return new JAXBElement<String>(_Annualized_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "paramParentOrganisationUnit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createParamParentOrganisationUnit(String value) {
        return new JAXBElement<String>(_ParamParentOrganisationUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "denominatorAggregationOperator")
    public JAXBElement<String> createDenominatorAggregationOperator(String value) {
        return new JAXBElement<String>(_DenominatorAggregationOperator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "individualMonthsThisYear")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIndividualMonthsThisYear(String value) {
        return new JAXBElement<String>(_IndividualMonthsThisYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "shortname")
    public JAXBElement<String> createShortname(String value) {
        return new JAXBElement<String>(_Shortname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last9Months")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast9Months(String value) {
        return new JAXBElement<String>(_Last9Months_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "tableName")
    public JAXBElement<String> createTableName(String value) {
        return new JAXBElement<String>(_TableName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "child")
    public JAXBElement<BigInteger> createChild(BigInteger value) {
        return new JAXBElement<BigInteger>(_Child_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "soFarThisYear")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSoFarThisYear(String value) {
        return new JAXBElement<String>(_SoFarThisYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last3Months")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast3Months(String value) {
        return new JAXBElement<String>(_Last3Months_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "geoCode")
    public JAXBElement<String> createGeoCode(String value) {
        return new JAXBElement<String>(_GeoCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "doIndicators")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDoIndicators(String value) {
        return new JAXBElement<String>(_DoIndicators_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "factor")
    public JAXBElement<BigInteger> createFactor(BigInteger value) {
        return new JAXBElement<BigInteger>(_Factor_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "denominator")
    public JAXBElement<String> createDenominator(String value) {
        return new JAXBElement<String>(_Denominator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "alternativename")
    public JAXBElement<String> createAlternativename(String value) {
        return new JAXBElement<String>(_Alternativename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "shortName")
    public JAXBElement<String> createShortName(String value) {
        return new JAXBElement<String>(_ShortName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "categoryOptionId")
    public JAXBElement<BigInteger> createCategoryOptionId(BigInteger value) {
        return new JAXBElement<BigInteger>(_CategoryOptionId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "individualQuartersThisYear")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIndividualQuartersThisYear(String value) {
        return new JAXBElement<String>(_IndividualQuartersThisYear_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "openingDate")
    public JAXBElement<String> createOpeningDate(String value) {
        return new JAXBElement<String>(_OpeningDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "source")
    public JAXBElement<BigInteger> createSource(BigInteger value) {
        return new JAXBElement<BigInteger>(_Source_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dhis2.org/ns/schema/dxf2", name = "last3To6Months")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLast3To6Months(String value) {
        return new JAXBElement<String>(_Last3To6Months_QNAME, String.class, null, value);
    }

}
