//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 03:44:18 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dhis2.org/ns/schema/dxf2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package org.hisp.dhis.importexport.dxf2.object;
