//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.30 at 03:44:18 PM GMT 
//


package org.hisp.dhis.importexport.dxf2.object;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reportTable" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}name"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}tableName"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}existingTableName"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}mode"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}regression"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doIndicators"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doCategoryOptionCombos"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doPeriods"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doOrganisationUnits"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}reportingMonth"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last3Months"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last6Months"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last9Months"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last12Months"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}soFarThisYear"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}soFarThisFinancialYear"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last3To6Months"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last6To9Months"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last9To12Months"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last12IndividualMonths"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}individualMonthsThisYear"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}individualQuartersThisYear"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}paramReportingMonth"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}paramParentOrganisationUnit"/>
 *                   &lt;element ref="{http://dhis2.org/ns/schema/dxf2}paramOrganisationUnit"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reportTable"
})
@XmlRootElement(name = "reportTables")
public class ReportTables {

    protected List<ReportTables.ReportTable> reportTable;

    /**
     * Gets the value of the reportTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportTables.ReportTable }
     * 
     * 
     */
    public List<ReportTables.ReportTable> getReportTable() {
        if (reportTable == null) {
            reportTable = new ArrayList<ReportTables.ReportTable>();
        }
        return this.reportTable;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}name"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}tableName"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}existingTableName"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}mode"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}regression"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doIndicators"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doCategoryOptionCombos"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doPeriods"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}doOrganisationUnits"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}reportingMonth"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last3Months"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last6Months"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last9Months"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last12Months"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}soFarThisYear"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}soFarThisFinancialYear"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last3To6Months"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last6To9Months"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last9To12Months"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}last12IndividualMonths"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}individualMonthsThisYear"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}individualQuartersThisYear"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}paramReportingMonth"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}paramParentOrganisationUnit"/>
     *         &lt;element ref="{http://dhis2.org/ns/schema/dxf2}paramOrganisationUnit"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "tableName",
        "existingTableName",
        "mode",
        "regression",
        "doIndicators",
        "doCategoryOptionCombos",
        "doPeriods",
        "doOrganisationUnits",
        "reportingMonth",
        "last3Months",
        "last6Months",
        "last9Months",
        "last12Months",
        "soFarThisYear",
        "soFarThisFinancialYear",
        "last3To6Months",
        "last6To9Months",
        "last9To12Months",
        "last12IndividualMonths",
        "individualMonthsThisYear",
        "individualQuartersThisYear",
        "paramReportingMonth",
        "paramParentOrganisationUnit",
        "paramOrganisationUnit"
    })
    public static class ReportTable {

        @XmlElement(required = true)
        protected BigInteger id;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String tableName;
        @XmlElement(required = true)
        protected String existingTableName;
        @XmlElement(required = true)
        protected String mode;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String regression;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String doIndicators;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String doCategoryOptionCombos;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String doPeriods;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String doOrganisationUnits;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String reportingMonth;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last3Months;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last6Months;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last9Months;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last12Months;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String soFarThisYear;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String soFarThisFinancialYear;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last3To6Months;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last6To9Months;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last9To12Months;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String last12IndividualMonths;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String individualMonthsThisYear;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String individualQuartersThisYear;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String paramReportingMonth;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String paramParentOrganisationUnit;
        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String paramOrganisationUnit;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the tableName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTableName() {
            return tableName;
        }

        /**
         * Sets the value of the tableName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTableName(String value) {
            this.tableName = value;
        }

        /**
         * Gets the value of the existingTableName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExistingTableName() {
            return existingTableName;
        }

        /**
         * Sets the value of the existingTableName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExistingTableName(String value) {
            this.existingTableName = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the regression property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegression() {
            return regression;
        }

        /**
         * Sets the value of the regression property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegression(String value) {
            this.regression = value;
        }

        /**
         * Gets the value of the doIndicators property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDoIndicators() {
            return doIndicators;
        }

        /**
         * Sets the value of the doIndicators property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDoIndicators(String value) {
            this.doIndicators = value;
        }

        /**
         * Gets the value of the doCategoryOptionCombos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDoCategoryOptionCombos() {
            return doCategoryOptionCombos;
        }

        /**
         * Sets the value of the doCategoryOptionCombos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDoCategoryOptionCombos(String value) {
            this.doCategoryOptionCombos = value;
        }

        /**
         * Gets the value of the doPeriods property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDoPeriods() {
            return doPeriods;
        }

        /**
         * Sets the value of the doPeriods property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDoPeriods(String value) {
            this.doPeriods = value;
        }

        /**
         * Gets the value of the doOrganisationUnits property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDoOrganisationUnits() {
            return doOrganisationUnits;
        }

        /**
         * Sets the value of the doOrganisationUnits property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDoOrganisationUnits(String value) {
            this.doOrganisationUnits = value;
        }

        /**
         * Gets the value of the reportingMonth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportingMonth() {
            return reportingMonth;
        }

        /**
         * Sets the value of the reportingMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportingMonth(String value) {
            this.reportingMonth = value;
        }

        /**
         * Gets the value of the last3Months property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast3Months() {
            return last3Months;
        }

        /**
         * Sets the value of the last3Months property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast3Months(String value) {
            this.last3Months = value;
        }

        /**
         * Gets the value of the last6Months property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast6Months() {
            return last6Months;
        }

        /**
         * Sets the value of the last6Months property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast6Months(String value) {
            this.last6Months = value;
        }

        /**
         * Gets the value of the last9Months property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast9Months() {
            return last9Months;
        }

        /**
         * Sets the value of the last9Months property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast9Months(String value) {
            this.last9Months = value;
        }

        /**
         * Gets the value of the last12Months property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast12Months() {
            return last12Months;
        }

        /**
         * Sets the value of the last12Months property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast12Months(String value) {
            this.last12Months = value;
        }

        /**
         * Gets the value of the soFarThisYear property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSoFarThisYear() {
            return soFarThisYear;
        }

        /**
         * Sets the value of the soFarThisYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSoFarThisYear(String value) {
            this.soFarThisYear = value;
        }

        /**
         * Gets the value of the soFarThisFinancialYear property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSoFarThisFinancialYear() {
            return soFarThisFinancialYear;
        }

        /**
         * Sets the value of the soFarThisFinancialYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSoFarThisFinancialYear(String value) {
            this.soFarThisFinancialYear = value;
        }

        /**
         * Gets the value of the last3To6Months property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast3To6Months() {
            return last3To6Months;
        }

        /**
         * Sets the value of the last3To6Months property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast3To6Months(String value) {
            this.last3To6Months = value;
        }

        /**
         * Gets the value of the last6To9Months property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast6To9Months() {
            return last6To9Months;
        }

        /**
         * Sets the value of the last6To9Months property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast6To9Months(String value) {
            this.last6To9Months = value;
        }

        /**
         * Gets the value of the last9To12Months property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast9To12Months() {
            return last9To12Months;
        }

        /**
         * Sets the value of the last9To12Months property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast9To12Months(String value) {
            this.last9To12Months = value;
        }

        /**
         * Gets the value of the last12IndividualMonths property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLast12IndividualMonths() {
            return last12IndividualMonths;
        }

        /**
         * Sets the value of the last12IndividualMonths property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLast12IndividualMonths(String value) {
            this.last12IndividualMonths = value;
        }

        /**
         * Gets the value of the individualMonthsThisYear property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndividualMonthsThisYear() {
            return individualMonthsThisYear;
        }

        /**
         * Sets the value of the individualMonthsThisYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndividualMonthsThisYear(String value) {
            this.individualMonthsThisYear = value;
        }

        /**
         * Gets the value of the individualQuartersThisYear property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIndividualQuartersThisYear() {
            return individualQuartersThisYear;
        }

        /**
         * Sets the value of the individualQuartersThisYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndividualQuartersThisYear(String value) {
            this.individualQuartersThisYear = value;
        }

        /**
         * Gets the value of the paramReportingMonth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParamReportingMonth() {
            return paramReportingMonth;
        }

        /**
         * Sets the value of the paramReportingMonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParamReportingMonth(String value) {
            this.paramReportingMonth = value;
        }

        /**
         * Gets the value of the paramParentOrganisationUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParamParentOrganisationUnit() {
            return paramParentOrganisationUnit;
        }

        /**
         * Sets the value of the paramParentOrganisationUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParamParentOrganisationUnit(String value) {
            this.paramParentOrganisationUnit = value;
        }

        /**
         * Gets the value of the paramOrganisationUnit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParamOrganisationUnit() {
            return paramOrganisationUnit;
        }

        /**
         * Sets the value of the paramOrganisationUnit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParamOrganisationUnit(String value) {
            this.paramOrganisationUnit = value;
        }

    }

}
