#!/bin/sh

TOMCAT_LOCAL=/usr/local/lib/tomcat
DHIS2_SOURCE_HOME=~/development/src/dhis2

case $1 in
start) 
  ${TOMCAT_LOCAL}/bin/startup.sh 
  ;;
stop)
  ${TOMCAT_LOCAL}/bin/shutdown.sh
  ;;
restart)
  ${TOMCAT_LOCAL}/bin/startup.sh
  ${TOMCAT_LOCAL}/bin/shutdown.sh
  ;;
log)
  tail -f ${TOMCAT_LOCAL}/logs/catalina.out
  ;;
update)
  sudo rm -rf ${TOMCAT_LOCAL}/webapps/dhis
  sudo rm ${TOMCAT_LOCAL}/webapps/dhis.war
  sudo cp ${DHIS2_SOURCE_HOME}/dhis-2/dhis-web/dhis-web-portal/target/dhis.war ${TOMCAT_LOCAL}/webapps/
  echo Tomcat updated with latest WAR from src code
  ;;
esac
exit 0

